# Scenario guide:
# - Scenario 1 & 2: IID / non-IID Single-Domain
#     → Only ONE of the num_*_clients should be non-zero
#
# - Scenario 3, 4 & 5: IID / non-IID / Highly non-IID Two-Domain
#     → Exactly TWO of the num_*_clients should be non-zero
#
# - Scenario 6: IID Multi-Domain
#     → ALL num_*_clients should be non-zero (none should be zero)

clients:
  num_digit_clients: 5         #  MNIST
  num_fashion_clients: 5       #  Fashion-MNIST
  num_kmnist_clients: 5       #  Kuzushiji-MNIST
  num_notmnist_clients: 5      #  NotMNIST

training:
  batch_size: 64               # Batch size for local training

experiment:
  scenario: 6                  # Set from 1 to 6 based on experiment type

optimizer:
  learning_rate: 0.0002
  betas:
    - 0.5
    - 0.999

settings:
  local_epochs: 1
  num_rounds: 2
